version: "2"

services:
### php
    php:
        build:
            context: ./php
            args:
                # php 容器 www-data用户密码
                - USERPASS=123456
                - INSTALL_YARN=false
        volumes_from:
            - php-fpm
            - nginx
            - mysql
            - redis
        links:
            - mysql
            - redis
        tty: true
        extra_hosts:
             # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
             - "wapi.4000669696.com:172.18.0.5"
             - "api.4000669696.com:172.18.0.5"
### php-fpm
    php-fpm:
        build: ./php-fpm
        volumes:
            - ../:/var/www/
            - ./logs/weiyuyan/:/data/laravel/storage/
            - ./logs/nginx/:/var/log/nginx/
        extra_hosts:
#             IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "wapi.4000669696.com:172.18.0.5"
            - "api.4000669696.com:172.18.0.5"
### nginx
    nginx:
        image: nginx:1.11.10-alpine
        ports:
            - "80:80"
        volumes_from:
            - php-fpm
        depends_on:
            - php-fpm
        links:
            - php-fpm
        volumes:
            - ./nginx/sites:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "wapi.4000669696.com:172.18.0.5"
            - "api.4000669696.com:172.18.0.5"
### mysql
    mysql:
        image: mysql:8.0.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "weiyuyan"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
        volumes:
            - ./mysql:/var/lib/mysql
### redis
    redis:
        image: redis:3.0.7
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
        command:
              redis-server --databases 128
#        volumes:
#            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
